# Generated by Django 5.0.6 on 2024-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flan",
            fields=[
                ("flan_id", models.AutoField(primary_key=True, serialize=False)),
                ("flan_name", models.CharField(max_length=64)),
                ("flan_description", models.TextField()),
                ("flan_image_url", models.URLField()),
                ("flan_slug", models.SlugField()),
                ("flan_is_private", models.BooleanField()),
            ],
        ),
    ]
