# Generated by Django 5.0.6 on 2024-07-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_flan_flan_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flan",
            name="flan_slug",
            field=models.SlugField(default="", null=True),
        ),
    ]
